### PR TITLE
initial work on tests

### PR DESCRIPTION
**Pull request by alexweber**
@TheCodeDestroyer @darthtrevino

### CODE REVIEW

**Comment by TheCodeDestroyer** [comment]
@alexweber Awesome, you did a lot of work! I'll also write some tests this week and maybe include Istanbul coverage or maybe wallaby.js would be better.

**Comment by alexweber** [comment]
@TheCodeDestroyer thanks for reviewing, I'm gradually getting more comfortable with the project and tooling... :)

**Comment by TheCodeDestroyer** [comment]
@alexweber This is currently failing how come?

**Comment by TheCodeDestroyer** [comment]
Seems to be ok, but travis is miss configured, I'll fix it later after its merged

**Comment by TheCodeDestroyer** [comment]
Seems to be ok, but travis is miss configured, I'll fix it later after its merged

**Pull request merged**
